/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrdRouteImport } from './routes/prd'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiPublishCronRouteImport } from './routes/api/publish/cron'
import { Route as ApiPublishNowRouteImport } from './routes/api/publish/now'
import { Route as ApiTiktokCreatorInfoRouteImport } from './routes/api/tiktok/creator-info'
import { Route as ApiOauthFacebookCallbackRouteImport } from './routes/api/oauth/facebook/callback'
import { Route as ApiOauthFacebookConnectRouteImport } from './routes/api/oauth/facebook/connect'
import { Route as ApiOauthFacebookPagesRouteImport } from './routes/api/oauth/facebook/pages'
import { Route as ApiOauthFacebookStartRouteImport } from './routes/api/oauth/facebook/start'
import { Route as ApiOauthTiktokCallbackRouteImport } from './routes/api/oauth/tiktok/callback'
import { Route as ApiOauthTiktokStartRouteImport } from './routes/api/oauth/tiktok/start'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdRoute = PrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublishCronRoute = ApiPublishCronRouteImport.update({
  id: '/api/publish/cron',
  path: '/api/publish/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishNowRoute = ApiPublishNowRouteImport.update({
  id: '/api/publish/now',
  path: '/api/publish/now',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokCreatorInfoRoute = ApiTiktokCreatorInfoRouteImport.update({
  id: '/api/tiktok/creator-info',
  path: '/api/tiktok/creator-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthFacebookCallbackRoute =
  ApiOauthFacebookCallbackRouteImport.update({
    id: '/api/oauth/facebook/callback',
    path: '/api/oauth/facebook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthFacebookConnectRoute = ApiOauthFacebookConnectRouteImport.update({
  id: '/api/oauth/facebook/connect',
  path: '/api/oauth/facebook/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthFacebookPagesRoute = ApiOauthFacebookPagesRouteImport.update({
  id: '/api/oauth/facebook/pages',
  path: '/api/oauth/facebook/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthFacebookStartRoute = ApiOauthFacebookStartRouteImport.update({
  id: '/api/oauth/facebook/start',
  path: '/api/oauth/facebook/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthTiktokCallbackRoute = ApiOauthTiktokCallbackRouteImport.update({
  id: '/api/oauth/tiktok/callback',
  path: '/api/oauth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthTiktokStartRoute = ApiOauthTiktokStartRouteImport.update({
  id: '/api/oauth/tiktok/start',
  path: '/api/oauth/tiktok/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/prd': typeof PrdRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/publish/cron': typeof ApiPublishCronRoute
  '/api/publish/now': typeof ApiPublishNowRoute
  '/api/tiktok/creator-info': typeof ApiTiktokCreatorInfoRoute
  '/api/oauth/facebook/callback': typeof ApiOauthFacebookCallbackRoute
  '/api/oauth/facebook/connect': typeof ApiOauthFacebookConnectRoute
  '/api/oauth/facebook/pages': typeof ApiOauthFacebookPagesRoute
  '/api/oauth/facebook/start': typeof ApiOauthFacebookStartRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/tiktok/start': typeof ApiOauthTiktokStartRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/prd': typeof PrdRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/publish/cron': typeof ApiPublishCronRoute
  '/api/publish/now': typeof ApiPublishNowRoute
  '/api/tiktok/creator-info': typeof ApiTiktokCreatorInfoRoute
  '/api/oauth/facebook/callback': typeof ApiOauthFacebookCallbackRoute
  '/api/oauth/facebook/connect': typeof ApiOauthFacebookConnectRoute
  '/api/oauth/facebook/pages': typeof ApiOauthFacebookPagesRoute
  '/api/oauth/facebook/start': typeof ApiOauthFacebookStartRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/tiktok/start': typeof ApiOauthTiktokStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/prd': typeof PrdRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/publish/cron': typeof ApiPublishCronRoute
  '/api/publish/now': typeof ApiPublishNowRoute
  '/api/tiktok/creator-info': typeof ApiTiktokCreatorInfoRoute
  '/api/oauth/facebook/callback': typeof ApiOauthFacebookCallbackRoute
  '/api/oauth/facebook/connect': typeof ApiOauthFacebookConnectRoute
  '/api/oauth/facebook/pages': typeof ApiOauthFacebookPagesRoute
  '/api/oauth/facebook/start': typeof ApiOauthFacebookStartRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/tiktok/start': typeof ApiOauthTiktokStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/prd'
    | '/privacy'
    | '/terms'
    | '/approvals'
    | '/calendar'
    | '/compose'
    | '/settings'
    | '/api/publish/cron'
    | '/api/publish/now'
    | '/api/tiktok/creator-info'
    | '/api/oauth/facebook/callback'
    | '/api/oauth/facebook/connect'
    | '/api/oauth/facebook/pages'
    | '/api/oauth/facebook/start'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/tiktok/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/prd'
    | '/privacy'
    | '/terms'
    | '/approvals'
    | '/calendar'
    | '/compose'
    | '/settings'
    | '/'
    | '/api/publish/cron'
    | '/api/publish/now'
    | '/api/tiktok/creator-info'
    | '/api/oauth/facebook/callback'
    | '/api/oauth/facebook/connect'
    | '/api/oauth/facebook/pages'
    | '/api/oauth/facebook/start'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/tiktok/start'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/prd'
    | '/privacy'
    | '/terms'
    | '/_authenticated/approvals'
    | '/_authenticated/calendar'
    | '/_authenticated/compose'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/publish/cron'
    | '/api/publish/now'
    | '/api/tiktok/creator-info'
    | '/api/oauth/facebook/callback'
    | '/api/oauth/facebook/connect'
    | '/api/oauth/facebook/pages'
    | '/api/oauth/facebook/start'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/tiktok/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrdRoute: typeof PrdRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublishCronRoute: typeof ApiPublishCronRoute
  ApiPublishNowRoute: typeof ApiPublishNowRoute
  ApiTiktokCreatorInfoRoute: typeof ApiTiktokCreatorInfoRoute
  ApiOauthFacebookCallbackRoute: typeof ApiOauthFacebookCallbackRoute
  ApiOauthFacebookConnectRoute: typeof ApiOauthFacebookConnectRoute
  ApiOauthFacebookPagesRoute: typeof ApiOauthFacebookPagesRoute
  ApiOauthFacebookStartRoute: typeof ApiOauthFacebookStartRoute
  ApiOauthTiktokCallbackRoute: typeof ApiOauthTiktokCallbackRoute
  ApiOauthTiktokStartRoute: typeof ApiOauthTiktokStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd': {
      id: '/prd'
      path: '/prd'
      fullPath: '/prd'
      preLoaderRoute: typeof PrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/publish/cron': {
      id: '/api/publish/cron'
      path: '/api/publish/cron'
      fullPath: '/api/publish/cron'
      preLoaderRoute: typeof ApiPublishCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish/now': {
      id: '/api/publish/now'
      path: '/api/publish/now'
      fullPath: '/api/publish/now'
      preLoaderRoute: typeof ApiPublishNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok/creator-info': {
      id: '/api/tiktok/creator-info'
      path: '/api/tiktok/creator-info'
      fullPath: '/api/tiktok/creator-info'
      preLoaderRoute: typeof ApiTiktokCreatorInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/facebook/callback': {
      id: '/api/oauth/facebook/callback'
      path: '/api/oauth/facebook/callback'
      fullPath: '/api/oauth/facebook/callback'
      preLoaderRoute: typeof ApiOauthFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/facebook/connect': {
      id: '/api/oauth/facebook/connect'
      path: '/api/oauth/facebook/connect'
      fullPath: '/api/oauth/facebook/connect'
      preLoaderRoute: typeof ApiOauthFacebookConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/facebook/pages': {
      id: '/api/oauth/facebook/pages'
      path: '/api/oauth/facebook/pages'
      fullPath: '/api/oauth/facebook/pages'
      preLoaderRoute: typeof ApiOauthFacebookPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/facebook/start': {
      id: '/api/oauth/facebook/start'
      path: '/api/oauth/facebook/start'
      fullPath: '/api/oauth/facebook/start'
      preLoaderRoute: typeof ApiOauthFacebookStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/tiktok/callback': {
      id: '/api/oauth/tiktok/callback'
      path: '/api/oauth/tiktok/callback'
      fullPath: '/api/oauth/tiktok/callback'
      preLoaderRoute: typeof ApiOauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/tiktok/start': {
      id: '/api/oauth/tiktok/start'
      path: '/api/oauth/tiktok/start'
      fullPath: '/api/oauth/tiktok/start'
      preLoaderRoute: typeof ApiOauthTiktokStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrdRoute: PrdRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublishCronRoute: ApiPublishCronRoute,
  ApiPublishNowRoute: ApiPublishNowRoute,
  ApiTiktokCreatorInfoRoute: ApiTiktokCreatorInfoRoute,
  ApiOauthFacebookCallbackRoute: ApiOauthFacebookCallbackRoute,
  ApiOauthFacebookConnectRoute: ApiOauthFacebookConnectRoute,
  ApiOauthFacebookPagesRoute: ApiOauthFacebookPagesRoute,
  ApiOauthFacebookStartRoute: ApiOauthFacebookStartRoute,
  ApiOauthTiktokCallbackRoute: ApiOauthTiktokCallbackRoute,
  ApiOauthTiktokStartRoute: ApiOauthTiktokStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
